name: 'Get Release Branches'
description: 'Determines if current branch is a release branch based on semantic-release config'
outputs:
  is-release-branch:
    description: 'Boolean indicating if current branch is a release branch'
runs:
  using: 'node20'
  main: 'dist/index.js'
