---
branches:
  - main
  - name: alpha
    prerelease: true
  - name: beta
    prerelease: true

plugins:
  - '@semantic-release/commit-analyzer'  # Plugin documentation: https://github.com/semantic-release/commit-analyzer
  - '@semantic-release/release-notes-generator'  # Plugin documentation: https://github.com/semantic-release/release-notes-generator
  - '@semantic-release/github'  # Plugin documentation: https://github.com/semantic-release/github
  - [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ]
  - [
      '@semantic-release/git',
      {
        "assets": ["CHANGELOG.md"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}",
      }
    ]
analyzeCommits:
  - path: '@semantic-release/commit-analyzer'
    preset: conventionalcommits
    presetConfig: true
generateNotes:
  - path: '@semantic-release/release-notes-generator'
    preset: conventionalcommits
    presetConfig: true
